"""DB_edit_table

Revision ID: ed45422f85ac
Revises: 61786f6cdbca
Create Date: 2024-05-10 18:15:33.780797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed45422f85ac'
down_revision: Union[str, None] = '61786f6cdbca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('registration', sa.DateTime(), nullable=False))
    op.add_column('orders', sa.Column('completion', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_orders_completion'), 'orders', ['completion'], unique=False)
    op.create_index(op.f('ix_orders_registration'), 'orders', ['registration'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_registration'), table_name='orders')
    op.drop_index(op.f('ix_orders_completion'), table_name='orders')
    op.drop_column('orders', 'completion')
    op.drop_column('orders', 'registration')
    # ### end Alembic commands ###
